### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by rozhuk-im** [butzist/ActivityLauncher#248]
```
Process: de.szalkowski.activitylauncher
PID: 5702
UID: 10087
Flags: 0x30c8bec5
Package: de.szalkowski.activitylauncher v50 (2.0.0)
Foreground: Yes
Process-Runtime: 1961
Build: Ulefone/Armor_X8_R_EEA/Armor_X8_R:11/RP1A.200720.011/1697170574:user/release-keys

java.lang.RuntimeException: Unable to start activity ComponentInfo{de.szalkowski.activitylauncher/de.szalkowski.activitylauncher.MainActivity}: android.view.InflateException: Binary XML file line #21 in de.szalkowsk
i.activitylauncher:layout/activity_main: Binary XML file line #24 in de.szalkowski.activitylauncher:layout/fragment_package_list: Binary XML file line #24 in de.szalkowski.activitylauncher:layout/fragment_package_li
st: Error inflating class androidx.recyclerview.widget.RecyclerView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3512)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3676)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2144)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
Caused by: android.view.InflateException: Binary XML file line #21 in de.szalkowski.activitylauncher:layout/activity_main: Binary XML file line #24 in de.szalkowski.activitylauncher:layout/fragment_package_list: Bin
ary XML file line #24 in de.szalkowski.activitylauncher:layout/fragment_package_list: Error inflating class androidx.recyclerview.widget.RecyclerView
Caused by: android.view.InflateException: Binary XML file line #24 in de.szalkowski.activitylauncher:layout/fragment_package_list: Binary XML file line #24 in de.szalkowski.activitylauncher:layout/fragment_package_l
ist: Error inflating class androidx.recyclerview.widget.RecyclerView
Caused by: android.view.InflateException: Binary XML file line #24 in de.szalkowski.activitylauncher:layout/fragment_package_list: Error inflating class androidx.recyclerview.widget.RecyclerView
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1138)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1099)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at de.szalkowski.activitylauncher.ui.PackageListFragment.y(SourceFile:10)
        at androidx.fragment.app.x.J(SourceFile:26)
        at androidx.fragment.app.v0.f(SourceFile:200)
        at androidx.fragment.app.v0.k(SourceFile:147)
        at androidx.fragment.app.q0.N(SourceFile:63)
        at androidx.fragment.app.q0.t(SourceFile:36)
        at androidx.fragment.app.v0.j(SourceFile:106)
        at androidx.fragment.app.v0.k(SourceFile:144)
        at androidx.fragment.app.e0.onCreateView(SourceFile:18)
        at androidx.fragment.app.a0.onCreateView(SourceFile:4)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1082)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1138)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1099)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1278)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1134)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1099)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at de.szalkowski.activitylauncher.MainActivity.onCreate(SourceFile:13)
        at android.app.Activity.performCreate(Activity.java:8012)
        at android.app.Activity.performCreate(Activity.java:7996)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3485)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3676)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2144)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
Caused by: android.content.res.Resources$NotFoundException: Drawable de.szalkowski.activitylauncher:drawable/fast_scroll_thumb with resource ID #0x7f080086
Caused by: android.content.res.Resources$NotFoundException: File res/v6.xml from drawable resource ID #0x7f080086
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:918)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:694)
        at android.content.res.Resources.loadDrawable(Resources.java:993)
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1006)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:981)
        at androidx.recyclerview.widget.RecyclerView.<init>(SourceFile:13)
        at androidx.recyclerview.widget.RecyclerView.<init>(SourceFile:1)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1138)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1099)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at de.szalkowski.activitylauncher.ui.PackageListFragment.y(SourceFile:10)
        at androidx.fragment.app.x.J(SourceFile:26)
        at androidx.fragment.app.v0.f(SourceFile:200)
        at androidx.fragment.app.v0.k(SourceFile:147)
        at androidx.fragment.app.q0.N(SourceFile:63)
        at androidx.fragment.app.q0.t(SourceFile:36)
        at androidx.fragment.app.v0.j(SourceFile:106)
        at androidx.fragment.app.v0.k(SourceFile:144)
        at androidx.fragment.app.e0.onCreateView(SourceFile:18)
        at androidx.fragment.app.a0.onCreateView(SourceFile:4)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1082)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1138)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1099)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1278)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1134)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1099)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at de.szalkowski.activitylauncher.MainActivity.onCreate(SourceFile:13)
        at android.app.Activity.performCreate(Activity.java:8012)
        at android.app.Activity.performCreate(Activity.java:7996)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3485)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3676)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2144)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
Caused by: android.content.res.Resources$NotFoundException: Drawable de.szalkowski.activitylauncher:drawable/shape_thumb with resource ID #0x7f0800e8
Caused by: android.content.res.Resources$NotFoundException: File res/9S.xml from drawable resource ID #0x7f0800e8
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:918)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:694)
        at android.content.res.Resources.loadDrawable(Resources.java:993)
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1006)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:981)
        at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:182)
        at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:126)
        at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:144)
        at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1402)
        at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1361)
        at android.content.res.ResourcesImpl.loadXmlDrawable(ResourcesImpl.java:981)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:904)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:694)
        at android.content.res.Resources.loadDrawable(Resources.java:993)
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1006)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:981)
        at androidx.recyclerview.widget.RecyclerView.<init>(SourceFile:13)
        at androidx.recyclerview.widget.RecyclerView.<init>(SourceFile:1)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1138)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1099)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at de.szalkowski.activitylauncher.ui.PackageListFragment.y(SourceFile:10)
        at androidx.fragment.app.x.J(SourceFile:26)
        at androidx.fragment.app.v0.f(SourceFile:200)
        at androidx.fragment.app.v0.k(SourceFile:147)
        at androidx.fragment.app.q0.N(SourceFile:63)
        at androidx.fragment.app.q0.t(SourceFile:36)
        at androidx.fragment.app.v0.j(SourceFile:106)
        at androidx.fragment.app.v0.k(SourceFile:144)
        at androidx.fragment.app.e0.onCreateView(SourceFile:18)
        at androidx.fragment.app.a0.onCreateView(SourceFile:4)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1082)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1138)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1099)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1278)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1134)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1099)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at de.szalkowski.activitylauncher.MainActivity.onCreate(SourceFile:13)
        at android.app.Activity.performCreate(Activity.java:8012)
        at android.app.Activity.performCreate(Activity.java:7996)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3485)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3676)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2144)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
Caused by: java.lang.UnsupportedOperationException: Can't convert to ComplexColor: type=0x1
        at android.content.res.ResourcesImpl.loadComplexColorForCookie(ResourcesImpl.java:1179)
        at android.content.res.ResourcesImpl.loadComplexColorFromName(ResourcesImpl.java:1055)
        at android.content.res.ResourcesImpl.loadColorStateList(ResourcesImpl.java:1134)
        at android.content.res.Resources.loadColorStateList(Resources.java:1139)
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:600)
        at android.graphics.drawable.GradientDrawable.updateGradientDrawableSolid(GradientDrawable.java:1701)
        at android.graphics.drawable.GradientDrawable.inflateChildElements(GradientDrawable.java:1585)
        at android.graphics.drawable.GradientDrawable.inflate(GradientDrawable.java:1404)
        at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:144)
        at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1402)
        at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1361)
        at android.content.res.ResourcesImpl.loadXmlDrawable(ResourcesImpl.java:981)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:904)
        ... 62 more

```

**Comment by butzist** [comment]
@rozhuk-im Hi Ivan, please try https://github.com/butzist/ActivityLauncher/releases/tag/2.0.1 - it should fix the issue
