### ISSUE TITLE
Fix the error of not being able to access the application when the device is installing the magisk module

### ISSUE THREAD

**Issue by f9nhcha** [butzist/ActivityLauncher#302]
Step 1: install Iconify module using iconify application https://github.com/mahmud0808/iconify
Step 2: Restart your device
Step 3: open this app and it crashed

This is my log file
[crash-de-szalkowski-activitylauncher-06_10-20-21-33_434.zip](https://github.com/user-attachments/files/17269504/crash-de-szalkowski-activitylauncher-06_10-20-21-33_434.zip)
```
FATAL EXCEPTION: Thread-2
Process: de.szalkowski.activitylauncher, PID: 7055
android.content.pm.PackageManager$NameNotFoundException: Unable to open /product/overlay/IconifyComponentWIFI15.apk
	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1759)
	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1737)
	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1765)
	at W0.p.<init>(SourceFile:113)
	at U0.c.get(SourceFile:91)
	at T0.a.get(SourceFile:14)
	at X0.w.b(SourceFile:7)
	at a1.a.run(SourceFile:3)
```

**Comment by drogga** [comment]
Please edit to include the log as a text in code or under expandable details.

**Comment by drogga** [comment]
Just as I suspected - caused by the overlay.
Which version are you using 1.15 2 ? (you can edit to include it in the OP), the latest one is 2.0.2, it's possible that the issue doesn't exist there. It's available on Play Store as beta, F-Droid and the sites for APKs (like Mirror/Combo/Pure/Fab, etc.).

**Comment by drogga** [comment]
Just as I suspected - caused by the overlay.
@f9nhcha Which version are you using 1.15.2 ? (you can edit to include it in the OP), the latest one is 2.0.2, it's possible that the issue doesn't exist there - it's available on Play Store as a Beta, F-Droid and the other sites for APKs (like Mirror/Combo/Pure/Fab, etc.).

**Comment by butzist** [comment]
Closing as stale - probably fixed
