### ISSUE TITLE
Looking for co-maintainers

### ISSUE THREAD

**Issue by butzist** [butzist/ActivityLauncher#51]
The project is looking for co-maintainers. Some of the open tasks are:

* Periodically update translations from Crowdin
* Improve Google Play store listing
* Monitor crash reports on Google Play
* Moderate bug reports

**Comment by msiejak** [comment]
I'd be willing to do some of that (I only speak English though, so no translations)
Could you email me some more details?

**Comment by butzist** [comment]
Hi Michael,

thanks for your interest. Do you have experience with building Android Apps with GitHub actions? The most urgent contribution for the project would be setting up some CI for the PRs and auto-publishing master to the Play store Alpha track. It's quite a bit of overhead building a new release at the moment as it involves:

* Build translations on Crowdin
* Download translations and integrate in code
* Update versions in Manifest etc
* Build (and before update Android Studio, as I don't use it too often)
* Upload to Play Store
* Create release with release notes etc etc

Would be awesome if we could integrate all this in GitHub actions.

Kind regards,
Adam

**Comment by drogga** [comment]
@msiejak ^

**Comment by msiejak** [comment]
I don't have much experience with github actions, but I'll work on it. And in the meantime, I would just manually build it like you have been doing. But I could most likely make a batch script for automating the translation process. I do have experience with android apps, though.
[msiejak.dev](https://msiejak.dev)

**Comment by vaimalaviya1233** [comment]
This article might give idea with [how to build with GitHub actions](https://medium.com/@josealfonsomora/publishing-android-apps-with-github-actions-3cb9a90396ca)

**Comment by drogga** [comment]
@butzist ^

**Comment by butzist** [comment]
@msiejak Then please go ahead and create pull-requests with translation updates from Crowdin. I have a script in the repo that used to fetch and extract the new translations - but not sure it is still functional.

**Comment by butzist** [comment]
For me automating the the build and release process would be the greatest help - for me it's always >1h of work to get out a new release. That's why it does not happen very often ;)

**Comment by butzist** [comment]
Update: Automated the build and release to beta track on Google Play.
Still looking for someone to
* Create releases
* Update translations from Crowdin

**Comment by Ethicalabhishek** [comment]
Hello
I can translate in Hindi .....
email:- dev@abhishek.icu

**Comment by intellis-dev** [comment]
Hi I'm interested in contributing to this project,
I have experience on developing Android apps and publishing them.I also have worked with GitHub actions for running a cron job to update database.
I have few ideas on how we can improve this app 
And coming to transalations,
I have not worked on it.

**Comment by drogga** [comment]
@intellis-dev Feel free to share your ideas and create PR, then we will see...

**Comment by butzist** [comment]
@intellis-dev That sounds great! We are open to new ideas for improving the app. In particular, I think the usability (UI/UX) of the app could be improved e.g. instead of context menu, navigate to a new summary/editing page that allows execution of all actions.

Regarding translations, the only thing we need, is someone proof-reading the translations on Crowdin and then creating a PR with the updated translations.

**Comment by drogga** [comment]
@butzist Please enable the repp'a "discussions" tab.
Thank You.

**Comment by intellis-dev** [comment]
@butzist 
Can we connect and discuss about this and when we are going to start development

**Comment by drogga** [comment]
@butzist Please enable the repo's "discussions" tab.
Thank You.

**Comment by butzist** [comment]
@drogga I created one discussion

**Comment by Kroshboy** [comment]
https://github.com/butzist/ActivityLauncher/issues/51#issue-777667246

**Comment by Nirmal4G** [comment]
@butzist I'm interested in maintaining build related code and improving CI and CD.

**Comment by edgard116** [comment]
Why ejecuta setting is so complicated now.   Triste is development or q?? Pleasy donde do this thing bigger and useless. Is so boring on this  days to do any configuration....

**Comment by oooooo99999** [comment]
> The project is looking for co-maintainers. Some of the open tasks are:
> 
> * Periodically update translations from Crowdin
> * Improve Google Play store listing
> * Monitor crash reports on Google Play
> * Moderate bug reports
>

**Comment by butzist** [comment]
Hi @cujoXavier,

atm the biggest help would be if someone would review the translations on crowdin and create PRs with updates.

**Comment by Kaitul** [comment]
Hi Adam,
I'm a translator from Taiwan, could you please add Traditional Chinese(zh-rTW) in Crowdin? I will help with it. Thanks!

**Comment by AbhiTheModder** [comment]
Hey, does the project still running 👀

**Comment by butzist** [comment]
Hey @AbhiTheModder , it is kind of running in maintenance mode - ie updating to new API versions and accepting PRs. But for the time being no new features from me.

**Comment by Kaitul** [comment]
Hi @butzist, can you add Traditional Chinese in Crowdin Project? I can help translate.

**Comment by ABOADAMm** [comment]
> Hi @butzist, can you add Traditional Chinese in Crowdin Project? I can help translate.

**Comment by butzist** [comment]
@Kaitul Sure, can do. Next time please create a separate issue for such requests.

**Comment by ABOADAMm** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.systemui/com.android.systemui.chooser.ChooserActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.IBinder android.os.Bundle.getBinder(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3931)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2284)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8337)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.IBinder android.os.Bundle.getBinder(java.lang.String)' on a null object reference
	at com.android.systemui.chooser.ChooserHelper.onChoose(ChooserHelper.java:40)
	at com.android.systemui.chooser.ChooserActivity.onCreate(ChooserActivity.java:32)
	at android.app.Activity.performCreate(Activity.java:8181)
	at android.app.Activity.performCreate(Activity.java:8147)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1330)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3737)
	... 12 more

**Comment by zhraa1992** [comment]
> The project is looking for co-maintainers. Some of the open tasks are:
> 
> * Periodically update translations from Crowdin
> * Improve Google Play store listing
> * Monitor crash reports on Google Play
> * Moderate bug reports

**Comment by Bolshau** [comment]
4b6f03f1a8fe93dec3a20e3683492f1c83156b0e

**Comment by Bolshau** [comment]
MT-Plugin-Language.mtsx

**Comment by JackEblan** [comment]
Bro, you need to update your code.
